name: Lint frontend

on:
  pull_request:
    paths:
      - 'invokeai/frontend/web/**'
  push:
    paths:
      - 'invokeai/frontend/web/**'

defaults:
  run:
    working-directory: invokeai/frontend/web

jobs:
  lint-frontend:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/checkout@v3
      - run: 'yarn install --frozen-lockfile'
      - run: 'yarn tsc'
      - run: 'yarn run madge'
      - run: 'yarn run lint --max-warnings=0'
      - run: 'yarn run prettier --check'
